; =================================================
; 1. THE UBUNTU LAPTOP (Prototyping Vision)
; =================================================
[env:native]
platform = native
build_flags = 
    !pkg-config --cflags --libs opencv4
    -I/usr/include/apriltag
    -lapriltag
; ONLY compile the laptop folder. Ignore the others.
build_src_filter = +<laptop/> -<espcam/> -<motor_esp/>

; =================================================
; 2. THE ESP32-CAM (The Eyes)
; =================================================
[env:espcam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
; ONLY compile the espcam folder. Ignore the others.
build_src_filter = +<espcam/> -<laptop/> -<motor_esp/>
board_build.partitions = min_spiffs.csv
upload_protocol = espota
upload_port = 192.168.4.3

; =================================================
; 3. THE STANDARD ESP32 (The Muscles)
; =================================================
[env:motor_esp]
platform = espressif32
board = esp32dev
framework = arduino

; Return your monitor back to standard speed
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_src_filter = +<motor_esp/> -<laptop/> -<espcam/>
monitor_port = /dev/ttyUSB0
lib_deps = ESP32Servo
board_build.partitions = min_spiffs.csv
